/**
 * YK.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterResponseDto { 
    succeeded?: boolean;
    token?: string | null;
    phone?: string | null;
    role?: string | null;
    errors?: Array<string>;
}

