/**
 * YK.WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RegisterCommand } from '../model/models';
import { RegisterResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param registerCommand 
     */
    accountRegisterPost(registerCommand: RegisterCommand, extraHttpRequestParams?: any): Observable<RegisterResponseDto>;

}
